### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by JarrydHuntley** [mdechatech/CharTweener#2]
Would you be able to add a license file to the repository so I know what use is allowed and how to credit?

This method makes it pretty easy: [https://stackoverflow.com/a/37895659](https://stackoverflow.com/a/37895659) .

Thanks!!

**Comment by Chillu1** [comment]
Super neat project, I would say it "replaces" DOTween prop, and since DOTween is open source licensed. It's completely legal. But could you also put an open source license on this repo? I would like to use DOTween with TMP in my project, but since currently you own all the right to it, I can't use if for any of my purposes. As pointed out by Jarryd
Nice work

**Comment by JarrydHuntley** [comment]
MIT license was added in commit f6a01ebe6bbc2eeaebae6f945f209791a2b99126. Good to go!
